# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-26 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('is_alive', models.BooleanField(default=True)),
                ('x', models.PositiveIntegerField(default=0)),
                ('y', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
